apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: traefik-no-redirect.yaml
  - target:
      kind: Deployment
      name: traefik
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args/3
        value: --providers.kubernetescrd.namespaces=mcp-platform,mcp-observability,mcp-servers,mcp-servers-org,mcp-servers-public
