apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: registry
  namespace: registry
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - registry.local
    secretName: registry-tls
  rules:
  - host: registry.local
    http:
      paths:
      - path: /v2
        pathType: Prefix
        backend:
          service:
            name: registry
            port:
              number: 5000
