apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../hostpath
patches:
  - path: ingress-tls.yaml
  - path: service-clusterip.yaml
    target:
      version: v1
      kind: Service
      name: registry
